<?xml version="1.0" encoding="utf-8"?>
<qroot>
<question>
<Title>Retrieving NAT type and external IP address</Title>
<Body>&lt;p&gt;So far I tried using &lt;a href=&quot;https://github.com/jtriley/pystun&quot; rel=&quot;nofollow noreferrer&quot;&gt;pystun&lt;/a&gt;, but following the manual:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;import stunnat_type, external_ip, external_port = stun.get_ip_info()&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;yields:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;&amp;gt;&amp;gt;&amp;gt; import stun&amp;gt;&amp;gt;&amp;gt; nat_type, external_ip, external_port = stun.get_ip_info()Traceback (most recent call last):  File &quot;&amp;lt;stdin&amp;gt;&quot;, line 1, in &amp;lt;module&amp;gt;  File &quot;/usr/local/lib/python3.6/dist-packages/stun/__init__.py&quot;, line 253, in get_ip_info    stun_host=stun_host, stun_port=stun_port)  File &quot;/usr/local/lib/python3.6/dist-packages/stun/__init__.py&quot;, line 186, in get_nat_type    _initialize()  File &quot;/usr/local/lib/python3.6/dist-packages/stun/__init__.py&quot;, line 93, in _initialize    dictValToAttr.update({items[i][1]: items[i][0]})TypeError: &#x27;dict_items&#x27; object does not support indexing&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;It looks like the repository is not maintained anymore. I found &lt;a href=&quot;https://github.com/phoemur/ipgetter&quot; rel=&quot;nofollow noreferrer&quot;&gt;ipgetter&lt;/a&gt; superfast for obtaining IP address, unfortunately it does not provide NAT type information. &lt;/p&gt;&lt;p&gt;What is the alternative way to retrieve both efficiently?&lt;/p&gt;</Body>
<Tags>python,python-3.x,python-3.6,stun</Tags>
</question>
<answer>
<Body>&lt;p&gt;It probably is a problem with &lt;code&gt;python&lt;/code&gt; versions, the original code of &lt;code&gt;pystun&lt;/code&gt; using &lt;code&gt;2.x&lt;/code&gt; and you using &lt;code&gt;3.x&lt;/code&gt;.&lt;/p&gt;&lt;p&gt;Looking at the &lt;a href=&quot;https://github.com/jtriley/pystun/blob/develop/stun/__init__.py#L93&quot; rel=&quot;nofollow noreferrer&quot;&gt;source code line where error originates&lt;/a&gt;, we can see that it calls the dictionaries &lt;code&gt;.items()&lt;/code&gt; method and tries to access its members by position.&lt;/p&gt;&lt;p&gt;Here is the problem:&lt;/p&gt;&lt;ul&gt;&lt;li&gt;In &lt;code&gt;python 2.x&lt;/code&gt;, &lt;a href=&quot;https://docs.python.org/2.7/library/stdtypes.html#dict.items&quot; rel=&quot;nofollow noreferrer&quot;&gt;&lt;code&gt;dict.items()&lt;/code&gt;&lt;/a&gt; returns a list of tuples.&lt;/li&gt;&lt;li&gt;In &lt;code&gt;python 3.x&lt;/code&gt;, &lt;a href=&quot;https://docs.python.org/3/library/stdtypes.html#dict.items&quot; rel=&quot;nofollow noreferrer&quot;&gt;&lt;code&gt;dict.items()&lt;/code&gt;&lt;/a&gt; returns a &lt;a href=&quot;https://docs.python.org/3/library/stdtypes.html#dict-views&quot; rel=&quot;nofollow noreferrer&quot;&gt;view&lt;/a&gt;, which cannot be accessed by position, only iterated over.&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;Short answer: you cannot use the &lt;code&gt;pystun&lt;/code&gt; repo with &lt;code&gt;python 3.x&lt;/code&gt;; maybe some patching can be done, or you can just copy and modify the source code yourself instead of relying on the external repo.&lt;/p&gt;</Body>
</answer>
</qroot>
