<?xml version="1.0" encoding="utf-8"?>
<qroot>
<question>
<Title>Tensorflow: freeze_graph - tensorflow.python.framework.errors_impl.DataLossError</Title>
<Body>&lt;p&gt;I am using Tensorflow-1.13 to create a deep-q model and use the following code to save it.&lt;/p&gt;&lt;pre&gt;&lt;code&gt;tf.global_variables_initializer()    tf.local_variables_initializer()saver = tf.train.Saver()saver.save(tf.get_default_session(), &#x27;deepq_0519&#x27;)&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;I got the following files:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;checkpointdeepq_0519.data-00000-of-00001deepq_0519.indexdeepq_0519.meta&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;I also use the code below to save the graph:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;tf.train.write_graph(sess.graph_def, &#x27;.&#x27;, &#x27;deepq_0519.pbtxt&#x27;)&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;and got:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;deepq_0519.pbtxt&lt;/code&gt;&lt;/pre&gt;&lt;hr&gt;&lt;p&gt;Finally, I tried to create a frozen graph using saved files:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;from tensorflow.python.tools import freeze_graphfreeze_graph.freeze_graph(&#x27;deepq_0519.pbtxt&#x27;, &quot;&quot;, False,                              &#x27;deepq_0519.data-00000-of-00001&#x27;,&quot;deepq/cond/Merge&quot;,                               &quot;&quot;, &quot;&quot;,                              &#x27;deepq_0519_frozen.pb&#x27;, True, &quot;&quot;                              )&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;But got the following error. Any idea what I did wrong? Thanks!&lt;/p&gt;&lt;pre&gt;&lt;code&gt;WARNING:tensorflow:From /Users/edamame/workspace/git/my_proj/venv/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:249: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed in a future version.Instructions for updating:Use tf.gfile.GFile.WARNING:tensorflow:From /Users/edamame/workspace/git/my_project/venv/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py:127: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.Instructions for updating:Use standard file APIs to check for files with this prefix.2019-05-19 16:00:06.642801: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA2019-05-19 16:00:06.646182: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ./deepq_0519.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?Traceback (most recent call last):  File &quot;my_freeze.py&quot;, line 6, in &amp;lt;module&amp;gt;    &#x27;deepq_0519_frozen.pb&#x27;, True, &quot;&quot;  File &quot;/Users/edamame/workspace/git/my_proj/venv/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py&quot;, line 363, in freeze_graph    checkpoint_version=checkpoint_version)  File &quot;/Users/edamame/workspace/git/my_proj/venv/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py&quot;, line 164, in freeze_graph_with_def_protos    reader = pywrap_tensorflow.NewCheckpointReader(input_checkpoint)  File &quot;/Users/edamame/workspace/git/my_proj/venv/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py&quot;, line 326, in NewCheckpointReader    return CheckpointReader(compat.as_bytes(filepattern), status)  File &quot;/Users/edamame/workspace/git/my_proj/venv/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py&quot;, line 528, in __exit__    c_api.TF_GetCode(self.status.status))tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./deepq_0519.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?&lt;/code&gt;&lt;/pre&gt;</Body>
<Tags>python,tensorflow</Tags>
</question>
<answer>
<Body>&lt;p&gt;I changed the code to:&lt;/p&gt;&lt;pre&gt;&lt;code&gt;from tensorflow.python.tools import freeze_graphfreeze_graph.freeze_graph(&#x27;deepq_0519.pbtxt&#x27;, &quot;&quot;, False,                              &#x27;deepq_0519&#x27;,&quot;deepq/cond/Merge&quot;,                               &quot;&quot;, &quot;&quot;,                              &#x27;deepq_0519_frozen.pb&#x27;, True, &quot;&quot;                              )&lt;/code&gt;&lt;/pre&gt;&lt;p&gt;basically remove &lt;code&gt;.data-00000-of-00001&lt;/code&gt; part and it works.&lt;/p&gt;</Body>
</answer>
</qroot>
