<?xml version="1.0" encoding="utf-8"?>
<qroot>
<question>
<Title>Error in Synchronize Translation Openerp 7</Title>
<Body>&lt;p&gt;I am getting this strange error when trying to synchronize terms in Openerp 7.&lt;/p&gt;&lt;p&gt;I had imported some terms for german language through a CSV file before but now I only have English installed.&lt;/p&gt;&lt;pre&gt;&lt;code&gt;OpenERP Server ErrorClient Traceback (most recent call last):File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/http.py&quot;, line 204, in dispatchresponse[&quot;result&quot;] = method(self, **self.params)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/controllers/main.py&quot;, line 1132, in call_buttonaction = self._call_kw(req, model, method, args, {})File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/controllers/main.py&quot;, line 1120, in _call_kwreturn getattr(req.session.model(model), method)(*args, **kwargs)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/session.py&quot;, line 42, in proxyresult=self.proxy.execute_kw(self.session._db,self.session._uid,self.session._password, self.model, method, args, kw)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/session.py&quot;, line 30, in proxy_methodresult = self.session.send(self.service_name, method, *args)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/session.py&quot;, line 103, in sendraise xmlrpclib.Fault(openerp.tools.ustr(e), formatted_info)Server Traceback (most recent call last):File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/web/session.py&quot;, line 89, in sendreturn openerp.netsvc.dispatch_rpc(service_name, method, args)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/netsvc.py&quot;, line 292, in dispatch_rpcresult = ExportService.getService(service_name).dispatch(method, params)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/service/web_services.py&quot;, line 626, in dispatchres = fn(db, uid, *params)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/osv/osv.py&quot;, line 188, in execute_kwreturn self.execute(db, uid, obj, method, *args, **kw or {})File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/osv/osv.py&quot;, line 131, in wrapperreturn f(self, dbname, *args, **kwargs)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/osv/osv.py&quot;, line 197, in executeres = self.execute_cr(cr, uid, obj, method, *args, **kw)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/osv/osv.py&quot;, line 185, in execute_crreturn getattr(object, method)(cr, uid, *args, **kw)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/openerp/addons/base/module/wizard/base_update_translations.py&quot;, line 47, in act_updatetools.trans_export(this.lang, [&#x27;all&#x27;], buf, &#x27;csv&#x27;, cr)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/opener/tools/translate.py&quot;, line 496, in trans_exporttranslations = trans_generate(lang, modules, cr)File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/opener/tools/translate.py&quot;, line 788, in trans_generatepush_translation(module, &#x27;model&#x27;, name, xml_name, encode(trad))File &quot;/usr/lib/python2.6/site-packages/openerp-7.0_20131124_002547-py2.6.egg/opener/tools/translate.py&quot;, line 648, in push_translationif not source or len(source.strip()) &amp;lt;= 1:AttributeError: &#x27;bool&#x27; object has no attribute &#x27;strip&#x27;&lt;/code&gt;&lt;/pre&gt;</Body>
<Tags>python,openerp</Tags>
</question>
<answer>
<Body>&lt;p&gt;I found the following solution to my problem:I had set a few custom boolean fields to &quot;translatable&quot; in my models. Un-checking the &quot;translatable&quot; property on them removed the errors.&lt;/p&gt;</Body>
</answer>
</qroot>
